<?php
$border_radius = array(
    '#bp-avatar-feedback.updated.success',
    '#bp-uploader-warning',
    '#buddypress #create-group-form input',
    '#buddypress #item-body form#whats-new-form',
    '#buddypress #item-header-avatar img',
    '#buddypress #message-threads thead tr th:first-child',
    '#buddypress #message-threads thead tr th:last-child',
    '#buddypress #reply-title small a span',
    '#buddypress .activity-avatar img.FB_profile_pic',
    '#buddypress .activity-content',
    '#buddypress .activity-list .activity-content .activity-header img.avatar',
    '#buddypress .activity-list li.mini .activity-avatar img.avatar',
    '#buddypress .comment-reply-link',
    '#buddypress .item-avatar img',
    '#buddypress .item-list-tabs ul li.last select',
    '#buddypress a.bp-primary-action span',
    '#buddypress a.button',
    '#buddypress div#item-header div#item-meta #latest-update p',
    '#buddypress div#item-header ul li a img',
    '#buddypress div#message',
    '#buddypress div#message-thread div.alt',
    '#buddypress div.ac-reply-avatar img',
    '#buddypress div.activity-meta a',
    '#buddypress div.bp-avatar-status p.success',
    '#buddypress div.bp-avatar-status p.warning',
    '#buddypress div.generic-button a',
    '#buddypress div.item-list-tabs#subnav ul',
    '#buddypress div.item-list-tabs#subnav ul li:first-child a',
    '#buddypress div.pagination .pagination-links .page-numbers:first-child',
    '#buddypress div.pagination .pagination-links .page-numbers:last-child',
    '#buddypress li.load-more',
    '#buddypress ul#groups-list li',
    '#buddypress ul#groups-list li div.item-avatar',
    '#buddypress ul#members-list li',
    '#buddypress ul#members-list li div.item-avatar',
    '#buddypress ul#members-list li div.item-avatar span.member-role',
    '#buddypress ul.item-list .activity-comments li img.avatar',
    '#content #buddypress table.profile-fields tr td.data',
    '#content-container #bbpress-forums button',
    '#content-container #bp-browse-button',
    '#content-container #buddypress #members-group-list #member-list li img',
    '#content-container #buddypress .button-nav li a',
    '#content-container #buddypress button.btn-cover-upload',
    '#content-container #buddypress div.activity-meta a.button:first-child',
    '#content-container #buddypress div.activity-meta a.button:last-child',
    '#content-container #buddypress input',
    '#content-container #create-group-form #item-nav',
    '#content-container #groups-directory-form #item-nav',
    '#content-container #learndash_next_prev_link a',
    '#content-container .box',
    '#content-container .bp_group #buddypress #item-nav.intern-box div.item-list-tabs ul li a',
    '#content-container .bp_members #buddypress #item-nav.intern-box div.item-list-tabs ul li a',
    '#content-container .infobox',
    '#content-container .intern-box#project-nav',
    '#content-container .intern-box#wiki-nav',
    '#content-container .masonry-layout .box .directory-item-fields',
    '#content-container .masonry-layout .box .intern-padding',
    '#content-container .ssfa_fileup_wrapper span',
    '#content-container article.content.type-multiverso .intern-padding.heading-container:after',
    '#content-container article.content.type-sfwd-certificates .intern-padding.heading-container:after',
    '#content-container article.content.type-sfwd-courses .intern-padding.heading-container:after',
    '#content-container article.content.type-sfwd-lessons .intern-padding.heading-container:after',
    '#content-container article.content.type-sfwd-quiz .intern-padding.heading-container:after',
    '#content-container article.content.type-sfwd-topic .intern-padding.heading-container:after',
    '#content-container article.content.type-sfwd-transactions .intern-padding.heading-container:after',
    '#content-container div.item-list-tabs ul li a span',
    '#content-container div.item-list-tabs ul li a span.count',
    '#content-container div.item-list-tabs ul li a span.no-count',
    '#content-container div.item-list-tabs ul li.current a span',
    '#content-container div.item-list-tabs ul li.current a span.count',
    '#content-container div.item-list-tabs ul li.current a span.no-count',
    '#content-container div.item-list-tabs ul li.selected a span',
    '#content-container div.item-list-tabs-project ul li a span',
    '#content-container div.item-list-tabs-project ul li.active a span',
    '#content-container div.item-list-tabs-wiki ul li a span',
    '#content-container div.item-list-tabs-wiki ul li.active a span',
    '#content-container div.wpcf7-response-output',
    '#dashboard .widget .intern-box',
    '#directory-search form button',
    '#featuredbox.directory-header .pagetitle',
    '#featuredbox.has-search form button',
    '#featuredbox.has-search form input',
    '#item-header',
    '#main-content input',
    '#main-search form input',
    '#map-directory-single',
    '#nav-languages>ul',
    '#nav-languages>ul li:first-child a',
    '#nav-languages>ul li:last-child a',
    '#page-wrapper .btn.btn-default',
    '#user-cover a img',
    '#user-thumb img',
    '#whats-new-avatar a img',
    '#woffice-coverprogressOuter',
    '#woffice-notifications-menu',
    '#woffice-poll-result .woffice-poll-result-answer .progress',
    '.ac-reply-avatar img',
    '.activity-avatar a img',
    '.blog-authorbox',
    '.blog-authorbox img',
    '.comment-list .comment-author.vcard img',
    '.intern-thumbnail',
    '.intern-thumbnail a',
    '.list-members img',
    '.progress.project-progress',
    '.project-members img',
    '.user-map-box img',
    '.widget .intern-padding ul.birthdays-list li img',
    '.widget.buddypress .bp-login-widget-user-avatar',
    '.widget.buddypress div.item-avatar img',
    '.widget.buddypress ul.item-list img.avatar',
    '.widget_woffice_usersmap #members-map-widget',
    '.woffice-notifications-item img',
    '.woffice-task .todo-assigned img',
    '.woffice-task header',
    '.woffice-task header label .checkbox-style:after',
    '.woffice-task header label .checkbox-style:before',
    '.woffice-task.has-note.unfolded header',
    '.wpcf7-checkbox span.wpcf7-list-item-label:before',
    '.wpcf7-radio span.wpcf7-list-item-label:before',
    'a.bp-title-button',
    'body.mce-fullscreen #content .mce-tinymce.mce-panel.mce-fullscreen>.mce-container-body.mce-stack-layout',
    'div.bp-progress',
    'input',
    'textarea',
    '.label',
    '.form-control',
    '#woffice-add-todo',
    '.widget.widget_search button',
    'body.layout-2 #woffice-login-right',
);