<?php
$color_light2_background = array(
    ' #buddypress form#whats-new-form textarea',
    ' #content-container .intern-box',
    ' .blog-authorbox',
    ' pre',
    ' #page-wrapper .wpcf7-checkbox span.wpcf7-list-item-label:before',
    ' #page-wrapper .wpcf7-radio span.wpcf7-list-item-label:before',
    ' #right-sidebar .widget:nth-child(odd)',
    ' #right-sidebar .widget:nth-child(odd) .intern-box.box-title h3',
    '.widget.widget_search input[type="text"]',
    ' .fw-accordion .fw-accordion-title',
    ' .fw-tabs-container .fw-tabs ul li',
    '#content-container div.item-list-tabs#subnav ul',
    ' #buddypress table.notifications tr.alt td',
    ' #buddypress table.notifications-settings tr.alt td',
    ' #buddypress table.profile-settings tr.alt td',
    ' #buddypress table.profile-fields tr.alt td',
    ' #buddypress table.wp-profile-fields tr.alt td',
    ' #buddypress table.messages-notices tr.alt td',
    ' #buddypress table.forum tr.alt td',
    ' #buddypress ul#groups-list li div.item-avatar',
    ' #buddypress ul#members-list li div.item-avatar',
    ' #navbar a:hover',
    ' #buddypress ul#activity-stream.item-list li:hover',
    ' #project-meta',
    ' #content-container #mv_file',
    ' #content-container #evcal_list .eventon_list_event p.no_events',
    ' #bbpress-forums div.odd',
    ' #bbpress-forums ul.odd',
    ' #bbpress-forums div.bbp-breadcrumb p',
    ' #bbpress-forums li.bbp-header',
    ' #bbpress-forums li.bbp-footer',
    ' #content #eventon_form .evoau_table .row:hover',
    ' #content #eventon_form p input',
    ' #content #eventon_form p textarea',
    ' #content #eventon_form p.dropdown_row select',
    ' #main-content .bpfb_form_container',
    ' .woffice-task header',
    ' #woffice-add-todo',
    ' #content-container #woffice-add-todo .heading > *',
    ' .woocommerce #content div.product div.summary',
    ' .woocommerce div.product div.summary',
    ' .woocommerce-page #content div.product div.summary',
    ' .woocommerce-page div.product div.summary',
    ' ul.woffice-minicart-top-products li:hover',
    ' .wiki-like-container p.wiki-like',
    ' #content-container #badgeos-achievements-filters-wrap',
    ' #content-container .ssfa-meta-container',
    ' #content-container .ssfa_fileup_container',
    ' #it-exchange-product .it-exchange-product-has-images .it-exchange-product-info',
	' #buddypress .standard-form select'
);