<?php
$color_light1_color = array(
    '#content-container .intern-box',
    ' #user-sidebar nav ul li a:hover',
    ' .wcContainer .wcMessages .wcMessage .wcMessageContent',
    ' #buddypress table.notifications thead tr',
    ' #buddypress table.notifications-settings thead tr',
    ' #buddypress table.profile-settings thead tr',
    ' #buddypress table.profile-fields thead tr',
    ' #buddypress table.wp-profile-fields thead tr',
    ' #buddypress table.messages-notices thead tr',
    ' #buddypress table.forum thead tr',
    ' #bbpress-forums li.bbp-header',
    ' form .woffice-task .todo-note',
    ' #content-container article.content.type-sfwd-quiz .intern-padding.heading-container:after',
    ' #content-container article.content.type-sfwd-courses .intern-padding.heading-container:after',
    ' #content-container article.content.type-sfwd-lessons .intern-padding.heading-container:after',
    ' #content-container article.content.type-sfwd-transactions .intern-padding.heading-container:after',
    ' #content-container article.content.type-sfwd-certificates .intern-padding.heading-container:after',
    ' #content-container article.content.type-multiverso .intern-padding.heading-container:after',
    ' #content-container article.content.type-sfwd-topic .intern-padding.heading-container:after',
    ' #buddypress .rtm-media-single-comments',
    ' #buddypress .rtmedia-like-info',
    '#buddypress .rtmedia-comments-container',
    ' #buddypress .rtm-comment-list li',
);