<?php
$colored_border_important = array(
    'input:focus',
    'textarea:focus',
    ' #content-container div.item-list-tabs ul li.current a span.no-count',
    ' #content-container div.item-list-tabs ul li.current a span.count',
    ' #content-container div.item-list-tabs ul li.selected a span',
    ' #content-container div.item-list-tabs-wiki ul li.active a span',
    ' #content-container div.item-list-tabs-project ul li.active a span',
    ' #featuredbox.has-search form input:focus',
    ' .woffice-task.is-done header label .checkbox-style:before',
    ' #woffice-minicart-top',
    ' #woffice-notifications-menu',
    ' #content-container .ui-state-active',
    ' #content-container .ui-widget-content .ui-state-active',
    ' #content-container .ui-widget-header .ui-state-active',
    ' #content-container .ui-state-hover',
    ' #content-container .ui-widget-content .ui-state-hover',
    ' #content-container .ui-widget-header .ui-state-hover',
    ' #content-container .ui-state-focus',
    ' #content-container .ui-widget-content .ui-state-focus',
    ' #content-container .ui-widget-header .ui-state-focus',
    '#geodir-wrapper .geodir-tabs .geodir-tab-active a',
);