<?php
$color_text_color = array(
    'body',
    ' p',
    ' .widget.widget_search input[type="text"]',
    '#content-container .fw-tabs-container .fw-tabs ul li a',
    ' .fw-accordion .fw-accordion-title',
    ' #featuredbox.has-search form input',
    ' #content-container div.item-list-tabs ul li a',
    ' #content-container div.item-list-tabs-wiki ul li a',
    ' #content-container div.item-list-tabs-project ul li a',
    ' table.profile-fields td.label',
    ' #item-header.no-featured',
    ' #user-sidebar nav ul li a',
    ' #content-container .eventon_fc_days .evo_fc_day:hover',
    ' .wcContainer *',
    'legend',
    '#right-sidebar a',
    ' a#can-scroll',
    '.text-body',
    '#buddypress #woffice-bp-sidebar .main-navs ul li a',
    '#navbar #nav-user a#user-thumb',
    ' #featuredbox .pagetitle #directory-search form #s',
    ' .woffice-notifications-item a',
    ' #featuredbox.has-search.search-buddypress form i.fa-spin',
    '#woffice-project-todo .woffice-project-filters li a.is-on'
);