<?php
$color_notifications_array = array(
    '#user-thumb .notifications',
    '#user-sidebar nav ul li a span.count',
    '#user-sidebar nav ul li a span.no-count',
    '#featuredbox.has-search form button',
    '#featuredbox.has-search form input[type="submit"]',
    '#content-container div.item-list-tabs ul li.current a span.no-count',
    '#content-container div.item-list-tabs ul li.current a span.count',
    '#content-container div.item-list-tabs ul li.current a span',
    '#content-container div.item-list-tabs ul li.selected a span',
    '#content-container div.item-list-tabs-wiki ul li.active a span',
    '#content-container div.item-list-tabs-project ul li.active a span',
    '#content-container div.item-list-tabs ul li a span.no-count',
    '#content-container div.item-list-tabs ul li a span.count',
    '#content-container div.item-list-tabs ul li a span',
    '#content-container div.item-list-tabs-wiki ul li a span',
    '#content-container div.item-list-tabs-project ul li a span',
    '#buddypress a.bp-primary-action span',
    '#buddypress #reply-title small a span',
    '#content-container div.wpcf7-validation-errors',
    '#nav-notification-trigger.active:after',
    '.notification-color',
    '.bp-navs ul li .count',
    '#geodir-wrapper .geodir-loc-bar .geodir_submit_search',
    '#geodir-wrapper .geodir-loc-bar .geodir_submit_search',
    '#directory-search form button[type="submit"]',
    '.single-gd_place .geodir-company_info .gdga-show-analytics',
);