<?php
$color_light3_array = array(
    '#content-container blockquote',
    ' #content-container blockquote::before',
    ' #content-container blockquote p',
    ' #content-container .comment-meta a',
    '#content-container .item-list-tabs ul li.last:after',
    ' #content-container .comment-metadata a',
    ' #content-container #buddypress div.activity-meta a.button',
    ' #navbar a',
    ' .woffice-loader',
    ' a.project-head span',
    ' #content-container .eventon_fc_days .evo_fc_day',
    '#content-container .ajde_evcal_calendar #evcal_head.calendar_header #evcal_cur',
    ' .wcContainer .wcMessage .wcMessageTime',
    ' .wp-caption .wp-caption-text',
    ' .bbp-pagination-count',
    '#content #evoau_form h3',
    '#evoau_form .label',
    ' #content-container a.password-lost',
    ' #content-container .gform_wrapper span.gform_description',
    ' #signup_form > p',
    '.birthdays-head i',
    '.widget .intern-padding ul.birthdays-list li i',
    ' .woffice-task header span.todo-date',
    ' .woocommerce .woocommerce-ordering',
    ' .woocommerce .woocommerce-result-count',
    ' .woocommerce ul.products li.product .price',
    ' .woocommerce .woocommerce-product-rating .star-rating',
    ' #content-container a.woocommerce-review-link',
    ' #content-container .woocommerce-tabs .tabs a',
    ' .woocommerce div.product form.cart .variations label',
    ' .woocommerce #content-container div.product p.price del .amount',
    ' .woffice-mini-cart-price',
    '.woffice-mini-cart-quantity',
    ' .woocommerce ul.cart_list li .star-rating',
    ' .woocommerce ul.product_list_widget li .star-rating',
    ' p.wiki-like span.count',
    ' #content-container .masonry-layout .box .directory-item-fields ul .directory-item-field i',
    ' .directory-category i',
    ' .directory-comments i',
    ' .directory-item-fields ul li i',
    ' #content-container .list-styled.list-wiki li.sub-category',
    ' #content-container .badgeos-required-achievements li::before',
    ' .metadatas-footer .post-metadatas',
    ' .poll-question-back',
    ' .woffice-xprofile-list span i',
    ' .woffice-notifications-item a span',
    ' .woffice-mini-cart-product-empty:before',
    ' .woffice-notification-empty:before',
    ' .post-metadatas li i',
    ' #content-container form .ui-accordion .ui-accordion-icons',
    ' #content-container .blog-shortcode-container h4 span',
    '#content-container .blog-shortcode-container .list-styled.list-arrow li::before',
    '.woffice-time-tracking-view p',
    '.woffice-time-tracking-head i',
    '.div[id^="ssfa-table-wrap"] a',
    '#woffice-project-todo .woffice-project-filters li a'
);