<?php
$colored_color_background = array(
    '.pace .pace-progress',
    '.progress-bar.progress-theme',
    'input[type="submit"]',
	'.btn.btn-primary',
	'.bg-primary',
    '#content-container #buddypress input[type="submit"]',
    '#buddypress #create-group-form input[type="button"]',
    '#content-container #bbpress-forums button[type="submit"]',
    '#right-sidebar .widget .intern-box.box-title::after',
    '#nav-sidebar-trigger:hover',
    '.widget.widget_search button',
    '#content-container .heading::before',
    '.widget_recent_entries .post-date',
    '#content-container div.item-list-tabs#subnav ul li.current a',
    'div.activity-meta a',
    '#main-content #buddypress div.generic-button a',
    '#buddypress .comment-reply-link',
    'a.bp-title-button',
    '.progress-bar',
    '#content-container #buddypress .button-nav li a',
    '#dashboard .widget .box-title::after',
    '#content-container .masonry-layout .box .box-title::after',
    '#content-container #buddypress button',
    '#buddypress ul#members-list li div.item-avatar span.member-role',
    '#content-container .mv-btn-success',
    '#content-container td.publish',
    '#content-container .mv-addfile-wrap a',
    '#content-container .mv-submitfields button',
    '#page-wrapper .wcContainer .wcMessage.wcCurrentUserMessage .wcMessageContent',
    '#content-container #bp-browse-button',
    '.gantt',
    '.gantt-day.weekend span',
    '.bbp-topic-tags a',
    '#content #eventon_form p #evoau_submit',
    '#content-container .mv-btn-success',
    '#content-container td.publish',
    '#content-container .mv-addfile-wrap a',
    '#content-container .mv-submitfields button',
    '#content-container div.item-list-tabs ul li.current a',
    '.wiki-like-container p.wiki-like.voted',
    '#content-container .badgeos-item-points:before',
    '#learndash_next_prev_link a',
    '#content-container .ssfa_fileup_wrapper span',
    '#buddypress div.pagination .pagination-links span',
    '#buddypress div.pagination .pagination-links a',
    '#rtmedia_create_new_album',
    '#dashboard .widget .box-title h3:before',
    '#dashboard .widget .box-title h3:after',
    '#dashboard .widget.evoFC_Widget h3.widget-title:before',
    '#dashboard .widget.evoFC_Widget h3.widget-title:after',
    '#content-container #buddypress .dataTables_wrapper .dataTables_paginate .paginate_button:not(.disabled)',
    '#dashboard.is-draggie .widget .widget-drag-button',
    'p.wiki-like.voted',
    '.woffice-colored-bg',
	'.geodir-viewall',
	'.badge-primary',
	'#buddypress #woffice-bp-sidebar .main-navs ul li.current a',
	'#geodir-wrapper .single-gd_place .geodir-post_left a',
    '#geodir-wrapper .single-gd_place .geodir-post_right a',
    ".learnpress-page .lp-button, .learnpress-page #lp-button",
    '#woffice-atmodal .at-submit',
    '#woffice-atmodal .at-comment',
    '#woffice-timeline-dialog #btn-dialog-close',
);