<?php
$color_light1_border = array(
    '#user-sidebar nav ul li a',
    '#content-container hr',
    ' #content-container .intern-box',
    ' #dashboard .widget.evoFC_Widget h3.widget-title',
    ' #page-wrapper .wpcf7-checkbox span.wpcf7-list-item-label:before',
    ' #page-wrapper .wpcf7-radio span.wpcf7-list-item-label:before',
    ' #right-sidebar .widget .intern-padding',
    ' #right-sidebar .widget .intern-box.box-title',
    '.main-menu li.menu-item-has-children ul li a',
    ' .main-menu li.menu-item-has-mega-menu div.mega-menu ul li a',
    ' #navigation-mobile ul li a',
    ' .main-menu li.menu-item-has-mega-menu div.mega-menu ul.sub-menu.mega-menu-row:first-child li a',
    '.widget.widget_search input[type="text"]',
    ' #content-container div.item-list-tabs ul li a',
    ' #buddypress div.item-list-tabs ul li:last-child a',
    ' #content-container div.item-list-tabs-wiki ul li a',
    ' #content-container div.item-list-tabs-project ul li a',
    ' #content-container div.item-list-tabs#subnav ul',
    ' #buddypress .activity-list li.mini',
    ' .ui-autocomplete.ui-front.ui-menu li',
    ' #buddypress table.notifications tr td.label',
    ' #buddypress table.notifications-settings tr td.label',
    ' #buddypress table.profile-fields tr td.label',
    ' #buddypress table.wp-profile-fields tr td.label',
    ' #buddypress table.messages-notices tr td.label',
    ' #buddypress table.forum tr td.label',
    ' #content-container .bp_activity #buddypress #item-nav.intern-box',
    ' #buddypress ul#groups-list li',
    ' #buddypress ul#members-list li',
    ' #content-container #item-nav.intern-box.group-header',
    ' #content-container div.item-list-tabs-wiki ul li:last-child a',
    '#content-container div.item-list-tabs-project ul li:last-child a',
    ' #nav-left',
    ' #projects-list li',
    '#project-meta',
    ' #project-meta .col-md-4',
    ' #content-container #evcal_list .eventon_list_event p.no_events',
    ' #content-container .ajde_evcal_calendar .eventon_events_list .eventon_list_event.event',
    ' #dashboard .widget .box-title',
    ' #content-container .masonry-layout .box .box-title',
    ' .wcContainer .wcMessages',
    ' .widget.buddypress div.item-options a',
    ' .bp-avatar-nav ul.avatar-nav-items li.current',
    ' .bp-avatar-nav ul',
    ' #bbpress-forums li.bbp-body ul.forum',
    ' #bbpress-forums li.bbp-body ul.topic',
    ' #bbpress-forums div.bbp-breadcrumb p',
    ' #bbpress-forums fieldset.bbp-form',
    ' #content #eventon_form',
    ' #content #eventon_form .evoau_table .row',
    ' #content #eventon_form p input',
    ' #content #eventon_form p textarea',
    ' #content #eventon_form p.dropdown_row select',
    ' #content-container .bbb-join select',
    ' #main-content #bbb-join-form.bbb-join',
    ' .woffice-task header label .checkbox-style:before',
    ' #content-container .badgeos-achievements-list-item',
    ' #content-container form .select2-container-multi .select2-choices',
);