<?php
$colored_color = array(
    '#content-container a',
    '#user-sidebar nav ul li a::before',
    '#content-container .dropcap',
    '.woffice-colored',
    '#page-wrapper .wpcf7-checkbox span.wpcf7-list-item-label:before',
    '#page-wrapper .wpcf7-radio span.wpcf7-list-item-label:before',
    '#content-container .fw-iconbox-image',
    '#main-search form button:hover',
    '#content-container .comment-meta a.url',
    '.special-404',
    '.comment-list .children li:before',
    '#content-container div.item-list-tabs ul li a:hover',
    '#content-container div.item-list-tabs-wiki ul li a:hover',
    '#content-container div.item-list-tabs-project ul li a:hover',
    '#content-container #buddypress div.activity-meta a.button:hover',
    '#activity-filter-select:after',
    'ul.project-meta-list li::before',
    '#content-container #buddypress div.activity-meta a.unfav.bp-secondary-action',
    '#content-container span.mv_user',
    '#content-container .eventon_fc_days .evo_fc_day.has_events',
    '.wcContainer .wcMessage.wcCurrentUserMessage .wcMessageContent:before',
    '.bbp-reply-post-date i',
    '#main-content #bpfb_addPhotos:before',
    '#main-content #bpfb_addVideos:before',
    '#main-content #bpfb_addLinks:before',
    '.animated-number h1',
    '.woocommerce div.product p.price',
    '.woocommerce div.product span.price',
    '#reviews .star-rating',
    '#woffice-minicart-top a',
    '.woffice-mini-cart-subtotal .amount',
    'span.like.alreadyvoted',
    '#content-container #learndash_lessons a',
    '#content-container #learndash_quizzes a',
    '#content-container .expand_collapse a',
    '#content-container .learndash_topic_dots a',
    '#content-container .learndash_topic_dots a > span',
    '#content-container #learndash_lesson_topics_list span a',
    '#content-container #learndash_profile a',
    '#content-container #learndash_profile a span',
    '.woffice-notifications-item a i.fa.component-icon',
    '#nav-buttons a.clicked',
    '.rtm-lightbox-container a',
    '.box .intern-padding h1 a',
    '.box .intern-padding h2 a',
    '.box .intern-padding h3 a',
    '.box .intern-padding h4 a',
    '.box .intern-padding h5 a',
    '.box .intern-padding h6 a',
    '.box .intern-padding a h1',
    '.box .intern-padding a h2',
    '.box .intern-padding a h3',
    '.box .intern-padding a h4',
    '.box .intern-padding a h5',
    '.box .intern-padding a h6',
    '#geodir-wrapper .geodir-tabs .geodir-tab-active a',
	'#buddypress #woffice-bp-sidebar .main-navs ul li a:before',
	'#main-search .woffice-search-results__item__title a',
    '#woffice-timeline-dialog .wotl_assignee_title a',
    '#woffice-timeline-dialog .wotl_assignee_title i',
    '#woffice-timeline-wrapper .wotl_assignee_title i'
);