<?php
$font_main = array(
    'body',
    'p',
    '.main-menu li a.fas',
	'.main-menu li a.fab',
    '#buddypress .mpp-g [class*=mpp-u]',
    'h3.mv-addfile-title',
    '#content #eventon_form p label',
    '#content #eventon_form p #evoau_submit',
    '.mv-file-managing',
    'table.mv-editfile th',
	'.widget_nav_menu li a.fa',
    '#dropdown-user-menu li a.fa',
    '[data-bp-tooltip]:after',
    '.dp_pec_wrapper .dp_pec_nav .selectric .label',
    '.dp_pec_accordion_wrapper .dp_pec_accordion_event h2',
    '.dp_pec_accordion_wrapper .dp_pec_accordion_event .dp_pec_accordion_event_center_text .pec_author',
	'.dp_pec_countdown_wrapper .dp_pec_countdown_event_center_text .pec_author',
	'.dp_pec_grid_wrapper li.dp_pec_grid_event span',
	'.dp_pec_grid_wrapper li.dp_pec_grid_event h2.dp_pec_grid_title',
	'.dp_pec_content .dp_pec_event_description',
	'.dp_pec_content .dp_pec_event_description p',
	'.dp_pec_wrapper .dp_pec_nav span',
	'.dp_pec_wrapper',
	'.dp_pec_new_event_wrapper',
	'.dp_pec_new_event_wrapper .dp_pec_submit_event, .dp_pec_new_event_wrapper .dp_pec_remove_event, .dp_pec_new_event_wrapper .dp_pec_cancel_booking, .pec_event_page_send_booking, .pec_action_btn',
    'table[id^="ssfa-table"].ssfa-minimalist',
);